### PR TITLE
Add support for unstructured libraries

### PR DESCRIPTION
**Pull request by ItzCrazyKns**

### CODE REVIEW

**Comment by homanp** [comment]
@elisalimli would you mind reviewing this please

**Comment by homanp** [comment]
@ItzCrazyKns How would one deploy this without having to load the whole unstructured dependancy which is quite big?

**Comment by ItzCrazyKns** [comment]
Maybe you can leave the unstructured installation part to the user, there isn't any better way for processing docs locally.

**Comment by homanp** [comment]
I don't think we can support this PR due to the large dependency size. It would be better for the user to run the Unstructured API separately: https://github.com/Unstructured-IO/unstructured-api

**Pull request closed without merging**
